spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.186.34:3306/xh_edu?useUnicode=true&characterEncoding=UTF8&autoReconnect=true
    username: root
    password: 'zjicm#2019'
  redis:
    timeout: 500
    database: 1
    host: 106.15.186.34
    port: 6379
    password: zjicm#2019
    pool:
      max-active: -1
      max-wait: -1
      max-idle: 8
      min-idle: 0

wxapp:
  appid: wx683a51f58dc68bf3
  secret: 955ce4a9dea7f1e2665cdd7b4101b2f7
  mchId: 10033027
  apiUrl:
    accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid={0}&secret={1}
    sendTemplateMsgUrl: https://api.weixin.qq.com/cgi-bin/message/wxopen/template/send?access_token={0}
    wxAppSessionUrl: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code
    wxAppCodeUnlimitUrl: https://api.weixin.qq.com/wxa/getwxacodeunlimit?access_token={0}
park-coupon:
  getAccessTokenUrl: https://park.ttsales.cn/park-coupon/wxa/accessToken
sendcouponsignaturekey:
  mch_id: 10033027
  notify_url: https://park.ttsales.cn/park-coupon-mch/wxPay/pay
  key: 3496e41f4c2644edb9be28257cb2d750
  trade_type: JSAPI
  orderUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
  appid: wx7c3ef40e839dd75d